server:
  port: 9090
  servlet:
    context-path: /download


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.129.188:3306/hbgm?characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: hbgm
    password: easipass
